# -*- coding: utf-8 -*-
"""TP_Persistance.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kIePP_JXvII0YiA3VV8iqzmBM3S-_YAK

# TP : Persistance des données avec Flask & MySQL

## Cas d’étude : Mini système de vote électronique

---

## 1. Introduction

Dans ce TP, nous allons construire une **mini application de vote électronique (e-voting)** inspirée de cas réels comme :

* élections scolaires
* votes associatifs
* consultations locales

L’objectif est de comprendre comment :

* stocker des données de manière fiable
* modéliser des entités métier (électeurs, candidats, votes)
* sécuriser des informations sensibles (mot de passe, vote)

---

## 2. Objectifs pédagogiques

À la fin du TP, vous serez capables de :

* utiliser un ORM (SQLAlchemy)
* créer et faire évoluer une base de données (Alembic)
* modéliser des relations entre entités
* implémenter un CRUD complet
* manipuler les données via Flask Shell
* introduire des notions de sécurité (hash, chiffrement)

---

## 3. Cas d’étude : Mini e-voting

### Acteurs

* **Organisateur** : crée une élection
* **Électeur** : vote
* **Candidat** : reçoit des votes

---

## 4. Structure du projet

```
project/
│
├── app.py
├── models.py
├── routes.py
├── config.py
├── templates/
```

---

## 5. Configuration MySQL

### config.py

```python
class Config:
    SQLALCHEMY_DATABASE_URI = "mysql+pymysql://root:password@localhost/evoting_db"
    SQLALCHEMY_TRACK_MODIFICATIONS = False
```

---

## 6. Initialisation Flask + ORM

### app.py

```python
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
from config import Config

db = SQLAlchemy()
migrate = Migrate()

def create_app():
    app = Flask(__name__)
    app.config.from_object(Config)

    db.init_app(app)
    migrate.init_app(app, db)

    from routes import main
    app.register_blueprint(main)

    return app
```

---

## 7. Modélisation (OOP + ORM)

### models.py

```python
from app import db

class Electeur(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    nom = db.Column(db.String(100), nullable=False)
    email = db.Column(db.String(120), unique=True)
    mot_de_passe = db.Column(db.String(200), nullable=False)

class Candidat(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    nom = db.Column(db.String(100), nullable=False)

class Vote(db.Model):
    id = db.Column(db.Integer, primary_key=True)

    electeur_id = db.Column(db.Integer, db.ForeignKey('electeur.id'))
    candidat_id = db.Column(db.Integer, db.ForeignKey('candidat.id'))

    electeur = db.relationship('Electeur')
    candidat = db.relationship('Candidat')
```

---

## Concepts introduits

* Une **classe = une table**
* Une **Foreign Key = relation**
* Un électeur peut voter pour un candidat
* Une table `Vote` représente une action métier

---

## 8. Migrations (Alembic)

```bash
flask db init
flask db migrate -m "initial schema evoting"
flask db upgrade
```

---

## 9. Utilisation du Flask Shell

```bash
flask shell
```

```python
from app import db
from models import Electeur, Candidat, Vote

e1 = Electeur(nom="Ali", email="ali@test.com", mot_de_passe="1234")
c1 = Candidat(nom="Candidate A")

db.session.add_all([e1, c1])
db.session.commit()

vote = Vote(electeur_id=e1.id, candidat_id=c1.id)
db.session.add(vote)
db.session.commit()
```

---

## 10. API REST (exemples)

### routes.py

```python
from flask import Blueprint, request, jsonify
from app import db
from models import Electeur, Vote

main = Blueprint('main', __name__)

@main.route('/electeurs', methods=['POST'])
def create_electeur():
    data = request.json

    electeur = Electeur(
        nom=data['nom'],
        email=data['email'],
        mot_de_passe=data['mot_de_passe']
    )

    db.session.add(electeur)
    db.session.commit()

    return jsonify({"id": electeur.id})


@main.route('/vote', methods=['POST'])
def voter():
    data = request.json

    vote = Vote(
        electeur_id=data['electeur_id'],
        candidat_id=data['candidat_id']
    )

    db.session.add(vote)
    db.session.commit()

    return jsonify({"message": "Vote enregistré"})
```

---

## 11. Interface simple (HTML)

Lister les candidats et voter via formulaire.

---

## 12. Introduction à la sécurité

Dans un système de vote, certaines données sont **sensibles** :

* mot de passe
* vote (choix de l’électeur)

---

### 12.1 Hash des mots de passe

Ne jamais stocker :

```python
mot_de_passe = "1234"
```

Utiliser un hash :

```python
from werkzeug.security import generate_password_hash

hashed = generate_password_hash("1234")
```

Vérification :

```python
from werkzeug.security import check_password_hash
check_password_hash(hashed, "1234")
```

---

### 12.2 Protection des votes (introduction)

Dans un vrai système :

* les votes doivent être **confidentiels**
* impossibles à modifier
* non traçables directement à un électeur

Approches possibles (introduction) :

* chiffrement des votes
* anonymisation
* signature numérique

---

## 13. Exercices

1. Empêcher un électeur de voter deux fois
2. Ajouter une table `Election`
3. Associer candidats à une élection
4. Compter les votes par candidat
5. Ajouter un champ `has_voted`

---

## 14. Guide de réflexion (important)

À la fin du TP, réfléchir à :

* Comment garantir qu’un électeur vote une seule fois ?
* Comment sécuriser les mots de passe ?
* Comment rendre un vote anonyme ?
* Peut-on faire confiance à la base de données ?

---
"""